### ISSUE TITLE
Doctest link error

### ISSUE THREAD

**Issue by UseAfterFree-177** [h1262216/crazys-wm-mod#17]
I'm getting link errors when I try to build with #14 in place. Is there a new prerequisite I need to install? If so, please update `README.md`.

-----

```
/usr/bin/ld: ../engine/libWMEngine.a(string.cpp.o): in function `_DOCTEST_ANON_FUNC_2()::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#1}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
crazys-wm-mod/src/engine/utils/string.cpp:103: undefined reference to `doctest::detail::ResultBuilder::ResultBuilder(doctest::assertType::Enum, char const*, int, char const*, char const*, char const*)'
/usr/bin/ld: crazys-wm-mod/src/engine/utils/string.cpp:103: undefined reference to `doctest::detail::ExpressionDecomposer::ExpressionDecomposer(doctest::assertType::Enum)'
/usr/bin/ld: crazys-wm-mod/src/engine/utils/string.cpp:103: undefined reference to `doctest::detail::ResultBuilder::setResult(doctest::detail::Result const&)'
...
```

**Comment by h1262216** [comment]
no, there shouldn't be any new dependency. I think these symbols are simply not defined when building the library, but only when linking the final executable. I think they come from these two lines in main.cpp
```
#define DOCTEST_CONFIG_IMPLEMENT
#include "doctest.h"
```

could you test whether adding these two lines in any arbitrary cpp file in the engine sources fixes these linker errors?

**Comment by h1262216** [comment]
can you check if #19 fixes your problem? With the object libraries, I don't think we technically need the static library anymore. Its main purpose is to ensure reduced dependencies between game and engine code (and in particular remove dependencies of engine code on game code, though that is not yet completely achieved).

**Comment by UseAfterFree-177** [comment]
I added those two lines to CLog.cpp. This time I got a "multiple definition" link error instead:
```
[ 32%] Linking CXX executable WMEngineTest
/usr/bin/ld: CMakeFiles/WMEngineObjects.dir/CLog.cpp.o:(.bss+0x0): multiple definition of `doctest::is_running_in_test'; CMakeFiles/WMEngineTest.dir/unittest.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/WMEngineObjects.dir/CLog.cpp.o: in function `doctest::detail::my_memcpy(void*, void const*, unsigned int)':
```

So except for the "arbitrary cpp file" part, I think that this fix could be made to work.

**Comment by h1262216** [comment]
OK, that makes sense though, if you compile the tests then the unittest.cpp also defines these symbols. so I guess that would need to be a new file which is not included in linking the engine unit tests. Hopefully #19 fixes both problems.

**Comment by UseAfterFree-177** [comment]
Now I get a successful build. One small thing is that the binaries got moved from 'my-build-dir/' to  'my-build-dir/src/game/'. A note in the README about that would be nice (or alternately, you could tell CMake to put them back in the old place).

**Comment by h1262216** [comment]
should be fixed now

**Comment by UseAfterFree-177** [comment]
Builds fine now, with the binaries back where they used to be.

Thanks!
