### ISSUE TITLE
wrong data in table

### ISSUE THREAD

**Issue by h1262216** [h1262216/crazys-wm-mod#26]
I (well, my fuzztester) just found a bug in the table sorting. The interface xml files specify one column as numeric, but it is in fact an Age column. Currently, this leads to a crash. I guess there are two ways we could handle this:
1) Abort the sort if something goes wrong during sorting
2) Prevent incompatible data to be entered into the table in the first place.

**Comment by h1262216** [comment]
Also, the Health column may contain the string DEAD. This crashes the game.
Maybe we should just sort all non-numeric values to the beginning/end in a numeric column.

**Comment by UseAfterFree-177** [comment]
- 1a (debug mode): Flag the error and crash the game. Type errors should be fixed.
 - 1b (release mode): Error out of the sort, log the error, and carry on. The game is still playable.
 - 2: Then Health should be its own type ("integer, or DEAD"), as age already is.
