### ISSUE TITLE
Could not find trait:

### ISSUE THREAD

**Issue by destinycatgod** [h1262216/crazys-wm-mod#45]
I have an issue that I cannot get past where my game immediately begins throwing an unskippable error at me with the text,

Could not find trait: 

Followed either by blank space, or gibberish text seemingly inserted from random character dialogue. Because I have so many girls at this point in the game (41) it's a bit hard to pin down an exact issue, but I'm assuming it's an issue with a character either having too much traits, or a character trying to pull a trait that doesn't exist.

As I said, this error is unskippable, as, once it's activated (usually through pressing More Detail) it boots me out to the girl management screen, and any subsequent attempts at going back into girl details just infinitely returns the error, until the game's restarted. And even then, it just re-activates itself if you attempt to go into More Details with ANY girl.

I also suspect it's got an issue to do with the random girls, because I did see somewhere that random girls apparently having huge numbers of traits breaks the game in weird ways.

Regardless, just wanted to post the bug. Image posted below. I am currently running 7.2.1-alpha5.

![image](https://user-images.githubusercontent.com/119298921/204257221-35b1870f-03c2-4b43-8576-48209e9f80c7.png)

**Comment by h1262216** [comment]
hi, thanks for the report. There is an error in the current code that handles therapy-type jobs that causes this. 
It's going to be fixed in the next version.

**Comment by h1262216** [comment]
Should be fixed now, it not please reopen.
