### ISSUE TITLE
Could not find trait: Dependant

### ISSUE THREAD

**Issue by Phonavis** [h1262216/crazys-wm-mod#46]
Happens if you click the slave market after buying the clinic, or if you go into the girl's "job aptitude" menu

Assuming it's from the trait actually being named "Dependent", also noticed this occured in several of the lua files so might wanna do a quick search to fix those

**Comment by Phonavis** [comment]
Did a quick replace with NPP on all instances in the raw files and it seems to have fixed it, would submit a commit but don't want to set up

**Comment by h1262216** [comment]
should be fixed with the new release.
