### ISSUE TITLE
What's the point of "Backup Saves"?

### ISSUE THREAD

**Issue by UseAfterFree-177** [h1262216/crazys-wm-mod#9]
Do you understand the usefulness of **Backup Saves**?

![image](https://user-images.githubusercontent.com/72233028/95675900-cca32a80-0bba-11eb-86a9-3797a67a424d.png)

It just gives you another copy of the same gamesave, so it does feel a bit pointless. You still can't have more than one gamesave in one playthrough -- two if you count the autosave.

**Comment by h1262216** [comment]
sorry, no I don't know why that exists

**Comment by UseAfterFree-177** [comment]
Well, it would help a bit against disk crashes, I suppose -- but anyone that seriously fears that should have a proper backup solution in place.

So I think it can be removed.

**Comment by h1262216** [comment]
I've asked in the discord chat if anybody knows any use for this, will let you know the answer

**Comment by h1262216** [comment]
there does not seem to be a reason for keeping backups, at least in this form

**Comment by UseAfterFree-177** [comment]
Nice to know. Thanks.

- [ ] TODO: Remove the current 'Backup Saves' feature.
- [ ] TODO: Replace it with something useful.
